spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: root
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
